# Permalinks
permalink:           pretty

# Setup
title:               computers are stupid
tagline:             and terrible
url:                 http://aawil.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              aaron wilson
  url:               https://github.com/aawil
  email:             aaronw@gmail.com 

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/aawil

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  about: '/about'
  posts: '/archive'
  # Feed: '/index.html'
